pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id "${quarkusPluginId}" version "${quarkusPluginVersion}"
    }
}
rootProject.name='ivy'
include 'modules:shell'
findProject(':modules:shell')?.name = 'shell'
include 'modules:core'
findProject(':modules:core')?.name = 'core'
include 'modules:html'
findProject(':modules:html')?.name = 'html'

