plugins {
    id 'io.quarkus'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-arc'
    implementation project(':ivy-core')
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
