quarkus.banner.enabled=false
quarkus.log.level=WARN
quarkus.log.category."io.quarkus".level=WARN

# native binary
quarkus.native.resources.includes=xyz/fokion/ivy/core/output/report.html,xyz/fokion/ivy/core/version.properties,META-INF/services/xyz.fokion.ivy.spi.Connector
quarkus.ssl.native=true
quarkus.native.additional-build-args=--enable-url-protocols=http\\,https
